Enhance build script with optimizations and TCP configs
Added basic optimizations and extra TCP configurations to the build script. Updated the script to fetch a new signing patch.

diff --git a/.github/workflows/NoSUSFS_test2-build.yml b/.github/workflows/NoSUSFS_test2-build.yml
--- a/.github/workflows/NoSUSFS_test2-build.yml
+++ b/.github/workflows/NoSUSFS_test2-build.yml
@@ -360,10 +360,30 @@ jobs:
               ;;
           esac
 
-          # Sign Builds
-          curl -L -o sign.patch "https://raw.githubusercontent.com/topnotchfreaks/kernel_patches/main/0001-scripts-sign-builds.patch" 
-          patch -p1 < sign.patch || echo "Warning: Strings patch failed"
+          # Basic optimizations
+          echo "CONFIG_KALLSYMS=y" >> "$CONFIG_FILE"
+          
+          # KSU Stuff
+          cat >> "$CONFIG_FILE" << 'EOF'
+          CONFIG_OVERLAY_FS=y
+          CONFIG_TMPFS_XATTR=y
+          CONFIG_TMPFS_POSIX_ACL=y
+          EOF
+          
+          # Extra TCP configs
+          cat >> "$CONFIG_FILE" << 'EOF'
+          CONFIG_TCP_CONG_ADVANCED=y
+          CONFIG_TCP_CONG_BIC=n
+          CONFIG_TCP_CONG_WESTWOOD=y
+          CONFIG_TCP_CONG_HTCP=n
+          CONFIG_TCP_CONG_BBR=y
+          CONFIG_DEFAULT_BBR=y
+          EOF
 
+          # Script sign patch
+          curl -L -o sign.patch "https://raw.githubusercontent.com/yougotme101/kernel_patches/main/0001-scripts-sign-builds.patch"
+          patch -p1 < sign.patch || echo "Warning: Strings patch failed"
+          
           # localversion
           # curl -L -o localversion.patch "https://raw.githubusercontent.com/topnotchfreaks/kernel_patches/main/0001-scripts-do-not-ship-full-auto_localversion.patch" 
           # patch -p1 < localversion.patch || echo "Warning: Strings patch failed"
