Refactor SuSFS system patches application step

diff --git a/.github/workflows/XStock-Multi.yml b/.github/workflows/XStock-Multi.yml
--- a/.github/workflows/XStock-Multi.yml
+++ b/.github/workflows/XStock-Multi.yml
@@ -225,6 +225,15 @@ jobs:
           
           cp -f susfs/kernel_patches/fs/susfs.c fs/
 
+      - name: "🔧 Apply SuSFS System Patches"
+        if: matrix.kernel.enable_ksu == true
+        working-directory: ./${{ env.KERNEL_LOC_DIR }}/${{ env.KERNEL_NAME }}
+        run: |
+          echo "Patching kernel system files for SuSFS..."
+          patch -p1 < susfs/kernel_patches/50_add_susfs_in_gki-android13-5.15.patch || echo "Hunks failed but continuing..."
+          rm -rf susfs
+
+          
           cp -f susfs4ksu/kernel_patches/fs/susfs.c fs/susfs.c \
             && echo "✔ Copied fs/susfs.c" \
             || { echo "❌ fs/susfs.c missing!"; exit 1; }
@@ -236,14 +245,6 @@ jobs:
           [ -f "susfs4ksu/kernel_patches/include/linux/susfs_def.h" ] && \
             cp -f susfs4ksu/kernel_patches/include/linux/susfs_def.h include/linux/susfs_def.h && \
             echo "✔ Copied susfs_def.h" || echo "⚠️ susfs_def.h not found, skipping"
-          
-      - name: "🔧 Apply SuSFS System Patches"
-        if: matrix.kernel.enable_ksu == true
-        working-directory: ./${{ env.KERNEL_LOC_DIR }}/${{ env.KERNEL_NAME }}
-        run: |
-          echo "Patching kernel system files for SuSFS..."
-          patch -p1 < susfs/kernel_patches/50_add_susfs_in_gki-android13-5.15.patch || echo "Hunks failed but continuing..."
-          rm -rf susfs
 
           # Define the config file path
           CONFIG_FILE="./arch/arm64/configs/${{ env.DEFCONFIG_NAME }}"
